git:
  submodules: false
branches:
  only:
    - master
before_script:
  - git submodule update --init --recursive
script:
  - set -o pipefail && xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" test | xcpretty
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
      xcode_workspace: ReactiveTask.xcworkspace
      xcode_scheme: ReactiveTask
      env: JOB=Xcode8
    - os: osx
      language: generic
      osx_image: xcode8
      script:
        - swift build
      env: JOB=SWIFTPM_DARWIN
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        - swift test
      env: JOB=SWIFTPM_LINUX
notifications:
  email: false
  slack:
    secure: Nh1mbn1RzYrI5tIY52gNrMy+PX1hdq2rIAJHxJjeiWjQDYfIoynhQ/2NIKs6Y0b0E5GIQEtF1fereyWdxcoEFGloY3cq4HZ7dgqr9kzOHrlDMp80fWbcoTqrgbOsKreFFtrv413d5+YcNkJvkYRfnxbuWLPZPszrcbw82TyRL60=
before_deploy:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage version
  - carthage build --no-skip-current --platform mac
  - carthage archive ReactiveTask
deploy:
  provider: releases
  api_key:
    secure: HL8FyVudN7johEi0hFOVR58NSVB8lFpx4HLzeZZoCz7nabj3LtavDoPF7c72nOYdrV6bhQiLiF2ocsYlfTrAyX5whO3532Lih3mE9NRePRGMyqnVD+4CnJUXusPxbesHq4IkMfEsq40KiqXKBa4XsiHZPhrQhmE+u7I4YIzjOYo=
  file: ReactiveTask.framework.zip
  skip_cleanup: true
  on:
    repo: Carthage/ReactiveTask
    tags: true
    condition: $JOB = Xcode8
